const User_Array =[
  {   id: "123478531",
        displayName: "Muhammad Masood Azhar",
        profileImage: require('../assets/1.jpg'),
        bio: "hi, my name is Muhammad Bilal. I am 12 year old and i am still studiying in islamin madrasa for islamic education for for the purpose of or as the purpose of my life. i want to spent whole of my life in this environment or like this . so this as the some intro to me for detail contact me.",
        email: "Muhammad Masood Azhar@gamil.com"}, 
    {
        id: "123478532",
        displayName: "Muhammad Usman",
        profileImage: require('../assets/2.jpg'),
        bio: "hi, my name is Muhammad Usman. I am 12 year old and i am still studiying in islamin madrasa for islamic education for for the purpose of or as the purpose of my life. i want to spent whole of my life in this environment or like this . so this as the some intro to me for detail contact me.",
        email: "Muhammad Usman@gamil.com"},
    {   id: "123478533",
        displayName: "Muhammad Hanzala",
        profileImage: require('../assets/3.jpg'),
        bio: " hi, my name is Muhammad Hanzala. I am 12 year old and i am still studiying in islamin madrasa for islamic education for for the purpose of or as the purpose of my life. i want to spent whole of my life in this environment or like this . so this as the some intro to me for detail contact me.",
        email: "Muhammad Hanzala@gamil.com"
      },
    {   id: "123478534",
        displayName: "Sheraz Ali",
        profileImage: require('../assets/4.jpg'),
        bio: " hi, my name is Sheraz Ali. I am 12 year old and i am still studiying in islamin madrasa for islamic education for for the purpose of or as the purpose of my life. i want to spent whole of my life in this environment or like this . so this as the some intro to me for detail contact me.",
        email: "Sheraz Ali@gamil.com"},
    {  id: "123478535",
        displayName: "Yasir Ali",
        profileImage: require('../assets/5.jpg'),
        bio: " hi, my name is Yasir Ali. I am 12 year old and i am still studiying in islamin madrasa for islamic education for for the purpose of or as the purpose of my life. i want to spent whole of my life in this environment or like this . so this as the some intro to me for detail contact me.",
        email: "Yasir Ali@gamil.com"},
    {   id: "123478536",
        displayName: "Shahbaz Ali",
        profileImage: require('../assets/6.jpg'),
        bio: " hi, my name is Shahbaz Ali. I am 12 year old and i am still studiying in islamin madrasa for islamic education for for the purpose of or as the purpose of my life. i want to spent whole of my life in this environment or like this . so this as the some intro to me for detail contact me.",
        email: "Shahbaz Ali@gamil.com"}, 
    {   id: "123478537",
        displayName: "Moeen Ali",
        profileImage: require('../assets/7.jpg'),
        bio: " hi, my name is Moeen Ali. I am 12 year old and i am still studiying in islamin madrasa for islamic education for for the purpose of or as the purpose of my life. i want to spent whole of my life in this environment or like this . so this as the some intro to me for detail contact me.",
        email: "Moeen Ali@gamil.com"}, 
    {   id: "123478538",
        displayName: "tufail Ahmad",
        profileImage: require('../assets/8.jpg'),
        bio: " hi, my name is tufail Ahmad. I am 12 year old and i am still studiying in islamin madrasa for islamic education for for the purpose of or as the purpose of my life. i want to spent whole of my life in this environment or like this . so this as the some intro to me for detail contact me.",
        email: "tufail Ahmad@gamil.com"},
     
      
        {   id: "123478539",
        displayName: "molana",
        profileImage: require('../assets/9.jpg'),
        bio: "hi, my name is molana Bilal. I am 12 year old and i am still studiying in islamin madrasa for islamic education for for the purpose of or as the purpose of my life. i want to spent whole of my life in this environment or like this . so this as the some intro to me for detail contact me.",
        email: "molana@gamil.com"},
        {   id: "123478540",
        displayName: "usama bin ladin",
        profileImage: require('../assets/10.jpg'),
        bio: " hi, my name is usama bin ladin I am 12 year old and i am still studiying in islamin madrasa for islamic education for for the purpose of or as the purpose of my life. i want to spent whole of my life in this environment or like this . so this as the some intro to me for detail contact me.",
        email: "usama bin ladin@gamil.com"},]

export default User_Array;